name: Deploy Client

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build and deploy client (replace with your actual build command)
      run: npm run build-client

    - name: Deploy to Azure App Service (client)
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-crm-service-client
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_CLIENT }}
